project:
  type: website
  resources:
    - forecasting/data/dataset/timesfm.csv

website:
  title: "PM₂.₅"
  navbar:
    left:
      - text: Forecasting
        href: forecasting/forecasting.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
